config/routes.rb
Foi::Application.routes.draw do

  get "home/index"

  resources :surveys do
    resources :questions
  end  
  resources :answer_choices
  resources :responses

  devise_for :users
  
  match 'response/:q_id' => 'Responses#new'
  

  root :to => "home#index"

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  has_many :answer_choices
  has_many :responses
  
  def next
    seq = self.survey.sequence 
    seq[seq.index(self)+1]
  end
  
  def last?
    (self.survey.sequence.last.id == self.id)
  end
  
  def process_answer_choices params
    create_answer_choices(params[:new_answer_choices])
    edit_answer_choices(params[:edit_answer_choices])    
  end
  
  def create_answer_choices answer_choices_sent
    return unless answer_choices_sent
    answer_choices_sent.each do |ac|
      self.answer_choices.build(ac)
    end
  end
  
  def edit_answer_choices answer_choices_sent
    return unless answer_choices_sent
    answer_choices_sent.each_pair do |id, ac_sent|
      ac = self.answer_choices.find_by_id(id)
      as.update_attributes(ac_sent)
    end
  end
    
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_filter :authenticate_user!
  
  # GET /survey/:survey_id/questions
  # GET /survey/:survey_id/questions.xml
  def index
    @survey = current_user.surveys.find(params[:survey_id])
    @questions = @survey.questions.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @questions }
    end
  end

  # GET /survey/:survey_id/questions/1
  # GET /survey/:survey_id/questions/1.xml
  def show
    public_view = !current_user || !!params[:public]
    @survey = (public_view ? Survey : current_user.surveys).find(params[:survey_id])
    @question = @survey.questions.find(params[:id])
    @response = @question.responses.build  if public_view
    
    respond_to do |format|
      format.html { render :template => "public_views/question.html.erb", :layout => "public"   if public_view }
      format.xml  { render :xml => @question }
    end
  end

  # GET /survey/:survey_id/questions/new
  # GET /survey/:survey_id/questions/new.xml
  def new
    @survey = current_user.surveys.find(params[:survey_id])
    @question = @survey.questions.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @question }
    end
  end

  # GET /survey/:survey_id/questions/1/edit
  def edit
    @survey = current_user.surveys.find(params[:survey_id])
    @question = @survey.questions.find(params[:id])
  end

  # POST /survey/:survey_id/questions
  # POST /survey/:survey_id/questions.xml
  def create
    @survey = current_user.surveys.find(params[:survey_id])
    @question = @survey.questions.build(params[:question])
    @question.process_answer_choices(params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to(survey_question_path(@survey, @question), :notice => 'Question was successfully created.') }
        format.xml  { render :xml => @question, :status => :created, :location => @question }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /survey/:survey_id/questions/1
  # PUT /survey/:survey_id/questions/1.xml
  def update
    @survey = current_user.surveys.find(params[:survey_id])
    @question = @survey.questions.find(params[:id])
    @question.process_answer_choices(params)
    
    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to(survey_question_path(@survey, @question), :notice => 'Question was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /survey/:survey_id/questions/1
  # DELETE /survey/:survey_id/questions/1.xml
  def destroy
    @survey = current_user.surveys.find(params[:survey_id])
    @question = @survey.questions.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to(survey_questions_url(@survey)) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  

end

app/views/questions/_form.html.erb
<% url = @question.new_record? ? survey_questions_path(@survey) : survey_question_url(@survey, @question) %>
<%= form_for @question, :url => url do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :q_text %><br />
    <%= f.text_area :q_text, :size => "50x4" %>
  </div>

  <div class="field" id="ans_type_block">
    <b>Answer type </b><br />
	<% ANSWER_TYPES.each_pair do |atype_id, a_type| %>
		<div class="ans_type">
		<%= f.radio_button :ans_type, atype_id %> 
		<%= f.label "ans_type_#{a_type[:id]}", raw(a_type[:desc]) %> <br/>
		</div>
	<% end %>
  </div>

  <div id="answer_choices_block">	
  </div>
			
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<br/>
<br/>
<br/>
<br/>

app/views/questions/edit.html.erb
<h1>Editing question</h1>
<%= form_for @question, :url => survey_question_url(@survey, @question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :q_text %><br />
    <%= f.text_area :q_text, :size => "50x4" %>
  </div>

  <div class="field" id="ans_type_block">
    <b>Answer type :</b>
  	<%= ANSWER_TYPES[@question.ans_type.to_s][:desc] %>
    <br/> <small>(answer type can't be edited. write a new question instead)</small>
  </div>

  <div id="answer_choices_block">	
	<% @question.answer_choices.each do |ac| %>
		<%= render :partial => "answer_choices/edit_answer_choice_#{@question.ans_type}", :locals => {:answer_choice => ac} %>
	<% end %>
	<div class='addon_link'><%= link_to '+', '/answer_choices/new?ans_type=2&addon=1', :remote=>true %></div>	
  </div>
			
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Show', survey_question_path(@survey, @question) %> |
<%= link_to 'Back', survey_questions_path(@survey) %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <tr>
    <th>Q text</th>
    <th>Ans type</th>
    <th>Survey</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.q_text %></td>
    <td><%= question.ans_type %></td>
    <td><%= link_to question.survey.name, survey_path(@survey) %></td>
	<td> &nbsp&nbsp&nbsp&nbsp </td>
    <td><%= link_to 'Show', survey_question_path(@survey, question) %></td>
    <td><%= link_to 'Edit', edit_survey_question_path(@survey, question) %></td>
    <td><%= link_to 'Destroy', survey_question_path(@survey, question), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question', new_survey_question_path(@survey) %>

app/views/questions/new.html.erb
<h1>New question</h1>

<% url = @question.new_record? ? survey_questions_path(@survey) : survey_question_url(@survey, @question) %>
<%= form_for @question, :url => survey_questions_path(@survey) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :q_text %><br />
    <%= f.text_area :q_text, :size => "50x4" %>
  </div>

  <div class="field" id="ans_type_block">
    <b>Answer type </b><br />
	<% ANSWER_TYPES.each_pair do |atype_id, a_type| %>
		<div class="ans_type">
		<%= f.radio_button :ans_type, atype_id %> 
		<%= f.label "ans_type_#{a_type[:id]}", raw(a_type[:desc]) %> <br/>
		</div>
	<% end %>
  </div>

  <div id="answer_choices_block">	
  </div>
			
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', survey_questions_path(@survey) %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question text:</b>
  <%= @question.q_text %>
</p>

<p>
  <b>Answer type:</b>
  <%= ANSWER_TYPES[@question.ans_type.to_s][:desc] %>
</p>

<p>
</p>
  <b>Answer options:</b>
  <ul>
  <% @question.answer_choices.each do |ac| %>
  	<li><%= ac.choice_text %></li>
  <% end %>
  </ul>
<p>
  <b>Survey:</b>
  <%= link_to @question.survey.name, survey_path(@survey)  %>
</p>


<%= link_to 'Edit', edit_survey_question_path(@survey, @question) %> |
<%= link_to 'Back', survey_questions_path(@survey) %>