config/routes.rb
Foi::Application.routes.draw do

  get "home/index"

  resources :surveys do
    resources :questions
  end  
  resources :answer_choices
  resources :responses

  devise_for :users
  
  match 'response/:q_id' => 'Responses#new'
  

  root :to => "home#index"

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  has_many :answer_choices
  has_many :responses
  
  def next
    seq = self.survey.sequence 
    seq[seq.index(self)+1]
  end
  
  def last?
    (self.survey.sequence.last.id == self.id)
  end
  
  def process_answer_choices params
    create_answer_choices(params[:new_answer_choices])
    edit_answer_choices(params[:edit_answer_choices])    
  end
  
  def create_answer_choices answer_choices_sent
    return unless answer_choices_sent
    answer_choices_sent.each do |ac|
      self.answer_choices.build(ac)
    end
  end
  
  def edit_answer_choices answer_choices_sent
    return unless answer_choices_sent
    answer_choices_sent.each_pair do |id, ac_sent|
      ac = self.answer_choices.find_by_id(id)
      as.update_attributes(ac_sent)
    end
  end
    
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController


  # GET /response/:q_id
  def new
    @question = Question.find params[:q_id]
    @survey = @question.survey
    @answer_choices = @question.answer_choices
    @response = Response.new(:question => @question)
  end

  # POST /surveys/:survey_id/answers
  def create
    @response = Response.new(params[:response])
    @question = @response.question
    @response.save
    render :text => "done"
    #redirect_to @question.last? ? survey_path(@survey) : survey_question_path(@survey, @question.next)
  end

end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/responses/new.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @question.q_text %>
</p>


<%= form_for @response do |f| %>

  <%= f.hidden_field :question_id %>

  <% case @question.ans_type.to_s %>
  <% when "1" %>

	<%= f.text_area :value %>	

  <% when "2" %>
	<ul><% @question.answer_choices.each do |ac| %>
    	<li><%= radio_button_tag "response[answer_choice_ids][]", ac.id %>
		<%= label_tag "response[answer_choices][]", ac.choice_text %> </li>
    <% end %></ul>

  <% when "3" %>
  	<ul><% @question.answer_choices.each do |ac| %>
  		<li><%= check_box_tag "response[answer_choice_ids][]", ac.id %>
		<%= label_tag "response[answer_choices][]", ac.choice_text %></li>
  	<% end %></ul>
  <% end %>

<p>
	<%= f.submit 'done' %>
</p>		
<% end %>

<p>
  <%= link_to "survey home", survey_path(@survey)  %>
</p>