config/routes.rb
Foi::Application.routes.draw do

  get "home/index"

  resources :surveys do
    resources :questions
  end  
  resources :answer_choices
  resources :responses

  devise_for :users
  
  match 'response/:q_id' => 'Responses#new'
  

  root :to => "home#index"

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :user
  has_many :questions
  
  def sequence
    @sequence = @sequence || generate_sequence
  end
  
  def generate_sequence
    self.questions.order("created_at")
  end
  
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  before_filter :authenticate_user!
  
  # GET /surveys
  # GET /surveys.xml
  def index
    @surveys = current_user.surveys.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @surveys }
    end
  end

  # GET /surveys/1
  # GET /surveys/1.xml
  def show  
    public_view = !current_user || params[:public]
    @survey = (public_view ? Survey : current_user.surveys).find(params[:id])

    respond_to do |format|
      format.html { render :template => "public_views/survey.html.erb", :layout => "public"   if public_view }
      format.xml  { render :xml => @survey }
    end
  end

  # GET /surveys/new
  # GET /surveys/new.xml
  def new
    @survey = current_user.surveys.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @survey }
    end
  end

  # GET /surveys/1/edit
  def edit
    @survey = current_user.surveys.find(params[:id])
  end

  # POST /surveys
  # POST /surveys.xml
  def create
    @survey = current_user.surveys.build(params[:survey])

    respond_to do |format|
      if @survey.save
        format.html { redirect_to(@survey, :notice => 'Survey was successfully created.') }
        format.xml  { render :xml => @survey, :status => :created, :location => @survey }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @survey.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /surveys/1
  # PUT /surveys/1.xml
  def update
    @survey = current_user.surveys.find(params[:id])

    respond_to do |format|
      if @survey.update_attributes(params[:survey])
        format.html { redirect_to(@survey, :notice => 'Survey was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @survey.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.xml
  def destroy
    @survey = current_user.surveys.find(params[:id])
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to(surveys_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<h1>Editing survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<h1>Listing surveys</h1>

<table>
  <tr>
    <th>Name</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @surveys.each do |survey| %>
  <tr>
    <td><%= survey.name %></td>
    <td><%= link_to 'Show', survey %></td>
    <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
    <td><%= link_to 'Destroy', survey, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1>New survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @survey.name %>
</p>

<p>
  <%= link_to "#{@survey.questions.count} question(s)", survey_questions_path(@survey) %>
</p>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>