config/routes.rb
Foi::Application.routes.draw do

  get "home/index"

  resources :surveys do
    resources :questions
  end  
  resources :answer_choices
  resources :responses

  devise_for :users
  
  match 'response/:q_id' => 'Responses#new'
  

  root :to => "home#index"

end

app/models/answer_choice.rb
class AnswerChoice < ActiveRecord::Base
  belongs_to :question  
end

app/controllers/answer_choices_controller.rb
class AnswerChoicesController < ApplicationController
  # GET /answer_choices
  # GET /answer_choices.xml
  def index
    @answer_choices = AnswerChoice.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @answer_choices }
    end
  end

  # GET /answer_choices/1
  # GET /answer_choices/1.xml
  def show
    @answer_choice = AnswerChoice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @answer_choice }
    end
  end

  # GET /answer_choices/new
  # GET /answer_choices/new.xml
  def new
    @answer_choice = AnswerChoice.new
    @ans_type_requested = params[:ans_type]
    @addon = params[:addon]
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @answer_choice }
      format.js { 
        render :layout => false 
      }
    end
  end

  # GET /answer_choices/1/edit
  def edit
    @answer_choice = AnswerChoice.find(params[:id])
  end

  # POST /answer_choices
  # POST /answer_choices.xml
  def create
    @answer_choice = AnswerChoice.new(params[:answer_choice])

    respond_to do |format|
      if @answer_choice.save
        format.html { redirect_to(@answer_choice, :notice => 'Answer choice was successfully created.') }
        format.xml  { render :xml => @answer_choice, :status => :created, :location => @answer_choice }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @answer_choice.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /answer_choices/1
  # PUT /answer_choices/1.xml
  def update
    @answer_choice = AnswerChoice.find(params[:id])

    respond_to do |format|
      if @answer_choice.update_attributes(params[:answer_choice])
        format.html { redirect_to(@answer_choice, :notice => 'Answer choice was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @answer_choice.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /answer_choices/1
  # DELETE /answer_choices/1.xml
  def destroy
    @answer_choice = AnswerChoice.find(params[:id])
    @answer_choice.destroy

    respond_to do |format|
      format.html { redirect_to(answer_choices_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/answer_choices_helper.rb
module AnswerChoicesHelper
end

app/views/answer_choices/_edit_answer_choice_2.html.erb
<div class="ans_choice">
  <%= label_tag :choice_text, "choice" %>
  <%= text_field_tag "edit_answer_choice[#{answer_choice.id}][choice_text]", answer_choice.choice_text  %>
  <%= link_to_function "x", "remove_ans_choice(event, true); " %>
</div>
	

app/views/answer_choices/_edit_answer_choice_3.html.erb
<div class="ans_choice">
  <%= label_tag :choice_text, "choice" %>
  <%= text_field_tag "edit_answer_choice[#{answer_choice.id}][choice_text]", answer_choice.choice_text  %>
  <%= link_to_function "x", "remove_ans_choice(event, true); " %>
</div>
	

app/views/answer_choices/_form.html.erb
<%= form_for(@answer_choice) do |f| %>
  <% if @answer_choice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer_choice.errors.count, "error") %> prohibited this answer_choice from being saved:</h2>

      <ul>
      <% @answer_choice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :choice_text %><br />
    <%= f.text_area :choice_text %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answer_choices/_new_answer_choice_2.html.erb
<div class="ans_choice">
  <%= label_tag :choice_text, "choice" %>
  <%= text_field_tag "new_answer_choices[][choice_text]"  %>
  <%= link_to_function "x", "remove_ans_choice(event, false); " %>
</div>
	

app/views/answer_choices/_new_answer_choice_3.html.erb
<div class="ans_choice">
  <%= label_tag :choice_text, "choice" %>
  <%= text_field_tag "new_answer_choices[][choice_text]"  %>
  <%= link_to_function "x", "remove_ans_choice(event, false); " %>
</div>
	

app/views/answer_choices/edit.html.erb
<h1>Editing answer_choice</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer_choice %> |
<%= link_to 'Back', answer_choices_path %>

app/views/answer_choices/index.html.erb
<h1>Listing answer_choices</h1>

<table>
  <tr>
    <th>Choice text</th>
    <th>Question</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @answer_choices.each do |answer_choice| %>
  <tr>
    <td><%= answer_choice.choice_text %></td>
    <td><%= answer_choice.question %></td>
    <td><%= link_to 'Show', answer_choice %></td>
    <td><%= link_to 'Edit', edit_answer_choice_path(answer_choice) %></td>
    <td><%= link_to 'Destroy', answer_choice, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Answer choice', new_answer_choice_path %>

app/views/answer_choices/new.html.erb
<h1>New answer_choice</h1>

<%= render 'form' %>

<%= link_to 'Back', answer_choices_path %>

app/views/answer_choices/new.js.erb
<% if @addon %>
	<% partial = "new_answer_choice_#{@ans_type_requested}" %>
	var html = "<%= escape_javascript(render :partial => partial) %>";
	$("#answer_choices_block").find(".addon_link").before(html);
	
<% else %>

<% case @ans_type_requested %>	
	<% when "1" %>
	$("#answer_choices_block").hide("slow").html('');	
	
	<% when "2" %>
	var html1 = "<%= escape_javascript(render :partial => 'new_answer_choice_2', :locals => {:no =>'1'}) %>"
	var html2 = "<%= escape_javascript(render :partial => 'new_answer_choice_2', :locals => {:no =>'2'}) %>"
	var html3 = "<%= escape_javascript(render :partial => 'new_answer_choice_2', :locals => {:no =>'3'}) %>"
	var html4 = "<%= escape_javascript(render :partial => 'new_answer_choice_2', :locals => {:no =>'4'}) %>"
	var more_link = "<div class='addon_link'><%= escape_javascript(link_to '+', '/answer_choices/new?ans_type=2&addon=1', :remote=>true) %></div>"
	
	var html = html1 + html2 + html3 + html4 + more_link ;
	$("#answer_choices_block").hide("slow").show("slow").html(html);	

	<% when "3" %>
	var html1 = "<%= escape_javascript(render :partial => 'new_answer_choice_3', :locals => {:no =>'1'}) %>"
	var html2 = "<%= escape_javascript(render :partial => 'new_answer_choice_3', :locals => {:no =>'2'}) %>"
	var html3 = "<%= escape_javascript(render :partial => 'new_answer_choice_3', :locals => {:no =>'3'}) %>"
	var html4 = "<%= escape_javascript(render :partial => 'new_answer_choice_3', :locals => {:no =>'4'}) %>"
	var more_link = "<div class='addon_link'><%= escape_javascript(link_to '+', '/answer_choices/new?ans_type=3&addon=1', :remote=>true) %></div>"
	
	var html = html1 + html2 + html3 + html4 + more_link ;
	$("#answer_choices_block").hide("slow").show("slow").html(html);
	
<% end %>
<% end %>

app/views/answer_choices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Choice text:</b>
  <%= @answer_choice.choice_text %>
</p>

<p>
  <b>Question:</b>
  <%= @answer_choice.question %>
</p>


<%= link_to 'Edit', edit_answer_choice_path(@answer_choice) %> |
<%= link_to 'Back', answer_choices_path %>